version: 'minty.abcxyz.dev/v2'

rule:
  if: |-
    assertion.iss == issuers.github &&
    assertion.repository_owner_id == '93787867' &&
    assertion.repository_id == '882980224'

scope:
  # Used by smoke-tests.yml which is called by ci.yml
  read-jit-runners:
    rule:
      if: |-
        assertion.workflow_ref.startsWith("abcxyz/github-action-dispatcher/.github/workflows/ci.yml")
    repositories:
      - 'github-action-dispatcher'
    permissions:
      contents: 'read'
      actions: 'read'

  create-tag:
    rule:
      if: |-
        assertion.job_workflow_ref == 'abcxyz/actions/.github/workflows/create-tag.yml@refs/heads/main' &&
        assertion.workflow_ref.startsWith('abcxyz/github-action-dispatcher/.github/workflows/create-tag.yml') &&
        assertion.ref == 'refs/heads/main' &&
        assertion.event_name == 'workflow_dispatch'
    repositories:
      - 'github-action-dispatcher'
    permissions:
      contents: 'write'
