version: 'minty.abcxyz.dev/v2'

rule:
  if: |-
    (
      assertion.iss == issuers.github &&
      assertion.repository_owner_id == '93787867' &&
      assertion.repository_id == '882980224' &&
      assertion.ref == 'refs/heads/main'
    ) || (
      assertion.iss == issuers.google &&
      assertion.email == "github-automation-bot@gha-gad-ci-a-832939.iam.gserviceaccount.com" // integration CI service account
    )

scope:
  make-pr:
    rule:
      if: |-
        (assertion.workflow_ref.startsWith("abcxyz/github-action-dispatcher/.github/workflows/integration-test.yml") ||
         assertion.workflow_ref.startsWith("abcxyz/github-action-dispatcher/.github/workflows/integration-test-minty.yml")) &&
        assertion.job_workflow_ref.startsWith("abcxyz/github-action-dispatcher/.github/workflows/integration-test-minty.yml")
    repositories:
      - 'github-action-dispatcher'
    permissions:
      contents: 'write'
      pull_requests: 'write'
  create-tag:
    rule:
      if: |-
        assertion.job_workflow_ref == 'abcxyz/actions/.github/workflows/create-tag.yml@refs/heads/main' &&
        assertion.workflow_ref.startsWith('abcxyz/github-action-dispatcher/.github/workflows/create-tag.yml') &&
        assertion.ref == 'refs/heads/main' &&
        assertion.event_name == 'workflow_dispatch'
    repositories:
      - 'github-action-dispatcher'
    permissions:
      contents: 'write'
