version: 'minty.abcxyz.dev/v2'

rule:
  if: |-
    assertion.iss == issuers.github &&
    assertion.repository_owner_id == '93787867' &&
    assertion.repository_id == '882980224' &&
    assertion.ref == 'refs/heads/main' &&
    assertion.workflow_ref == assertion.job_workflow_ref

scope:
  make-pr:
    rule:
      if: |-
        assertion.workflow_ref.startsWith("abcxyz/github-action-dispatcher/.github/workflows/.yml") &&
        (assertion.event_name == 'workflow_dispatch' ||
         assertion.event_name == 'workflow_dispatch' == 'workflow_call' )
    repositories:
      - 'github-action-dispatcher'
    permissions:
      contents: 'write'
      pull_requests: 'write'
