name: 'build_runner_container'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'runner/**'
  workflow_dispatch:

env:
  WIF_PROVIDER: 'projects/727875687543/locations/global/workloadIdentityPools/github-actions-on-gcp-p-a63b4c/providers/github-actions-on-gcp-p-a63b4c'
  WIF_SERVICE_ACCOUNT: 'github-automation-bot@gha-on-gcp-p-a63b4c.iam.gserviceaccount.com'
  GAR_LOCATION: 'us'
  GAR_IMAGE_NAME: 'ghss-artifacts-p-25/docker-images/gha-runner'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  # #18 This is not currently working, there doesn't seem to be a way to set the working directory so the Dockerfile fails to copy in start_runner.sh
  # build_and_publish:
  #   uses: 'abcxyz/pkg/.github/workflows/maybe-build-docker.yml@main'
  #   with:
  #     dockerfile: './runner/Dockerfile'
  #     artifact_registry_image_name: 'us-docker.pkg.dev/ghss-artifacts-p-25/gha-runner'
  #     workload_identity_provider: 'projects/727875687543/locations/global/workloadIdentityPools/github-actions-on-gcp-p-a63b4c/providers/github-actions-on-gcp-p-a63b4c'
  #     wif_service_account: 'github-automation-bot@gha-on-gcp-p-a63b4c.iam.gserviceaccount.com'
  #     extra_hash_file1: './runner/start_runner.sh'
  #     extra_tag1: 'latest'

  build_and_publish:
    name: 'Build and publish Docker image'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@98ddc00a17442e89a24bbf282954a3b65ce6d200' # ratchet:google-github-actions/setup-gcloud@v2
        with:
          version: '460.0.0'

      - uses: 'docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc' # ratchet:docker/login-action@v2
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: 'Build Docker image'
        id: 'push'
        uses: 'docker/build-push-action@master'
        with:
          context: './runner'
          file: './runner/Dockerfile'
          tags: '${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GAR_IMAGE_NAME }}:latest'
          push: true
