# Copyright 2025 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Self-Hosted Integration Tests'

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'The runner environment to use for jobs.'
        type: 'choice'
        options:
          - 'self-hosted'
          - 'ubuntu-latest'
  workflow_run:
    # Run this workflow after either of the other build/deploys run.
    workflows:
      - 'build_runner.yml'
      - 'build_webhook.yml'
    types:
      - 'completed'
    branches:
      - 'main'

jobs:
  test-github-script-action:
    runs-on: "${{ inputs.runs-on || 'self-hosted' }}"
    steps:
      - name: 'Hello world script'
        uses: 'actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea' # ratchet:actions/github-script@v7
        with:
          script: |-
            core.info("Hello World");

  test-js-action:
    runs-on: "${{ inputs.runs-on || 'self-hosted' }}"
    steps:
      - name: 'Run action'
        uses: 'actions/hello-world-javascript-action@ad41a6c27317e688719c813b0d6a25685a9bce54' # ratchet:actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'self hosted runner users'

  check-docker-volume-mount:
    # This test is to check Docker-in-Docker volume mounting. It's possible that the docker run command will succeed but not properly mount the files and workflows subsequently fail.
    name: 'Verify Docker-in-Docker volume mounts on the self-hosted runner'
    runs-on: "${{ inputs.runs-on || 'self-hosted' }}"
    steps:
      - name: 'Checkout Repository'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - name: 'Test GITHUB_WORKSPACE mount inside Docker'

        id: 'mount-check'
        shell: 'bash'
        run: |
          echo "Host GITHUB_WORKSPACE is: $GITHUB_WORKSPACE"
          echo "Contents of GITHUB_WORKSPACE on host:"
          ls -laR "$GITHUB_WORKSPACE"


          echo "Running Docker container to check mounted workspace..."
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/github/workspace" \
            -w "/github/workspace" \
            alpine sh -c "ls -laR" > docker_ls_output.txt

          echo "--- Output from inside container (docker_ls_output.txt) ---"
          cat docker_ls_output.txt
          echo "---------------------------------------------------------"

          if grep -q "terraform" docker_ls_output.txt; then
            echo "::notice file=check-docker-volume-mount.yml::Docker volume mount appears to be working correctly."
            echo "status=PASSED" >> "$GITHUB_OUTPUT"
          else
            echo "::error file=check-docker-volume-mount.yml::Docker volume mount failed or is empty."
            echo "status=FAILED" >> "$GITHUB_OUTPUT"
            exit 1 # Fail the step if the mount is empty
          fi

  check-go-test-self:
    uses: 'abcxyz/actions/.github/workflows/go-test.yml@main' # ratchet:exclude
    with:
      directory: 'pkg/'
      runs-on: "\"${{ inputs.runs-on || 'self-hosted' }}\""

  run-lint-tests-pkg:
    name: 'Run Lint Suite on abcxyz/pkg'
    uses: './.github/workflows/integration-test-lint.yml'
    with:
      repo-to-lint: 'abcxyz/pkg'
      ref: 'main'
      runs-on: "${{ inputs.runs-on || 'self-hosted' }}"

  run-lint-tests-java-repo:
    name: 'Run Lint Suite on abcxyz/lumberjack to test a repo with java'
    uses: './.github/workflows/integration-test-lint.yml'
    with:
      repo-to-lint: 'abcxyz/lumberjack'
      ref: 'main'
      runs-on: "${{ inputs.runs-on || 'self-hosted' }}"

  test-buildx-buildkit-functionality:
    name: 'Test buildx Buildkit functionality'
    uses: './.github/workflows/integration-test-buildx-buildkit.yml'
    with:
      runs-on: "${{ inputs.runs-on || 'self-hosted' }}"

  test-create-pull-request-minty:
    name: 'Test Create Pull Request flow with Minty'
    uses: './.github/workflows/integration-test-minty.yml'
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      runs-on: "${{ inputs.runs-on || 'self-hosted' }}"

  test-github-functionality:
    name: 'Test GitHub functionality'
    uses: './.github/workflows/integration-test-gh.yaml'
    with:
      runs-on: "${{ inputs.runs-on || 'self-hosted' }}"

  test-gcp-functionality:
    name: 'Test GCP functionality'
    uses: './.github/workflows/integration-test-gcp.yml'
    permissions:
      id-token: 'write'
    with:
      runs-on: "${{ inputs.runs-on || 'self-hosted' }}"

  setup-actions:
    name: 'Test setup actions'
    uses: './.github/workflows/integration-test-setup.yml'
    with:
      runs-on: "${{ inputs.runs-on || 'self-hosted' }}"

  setup-binary:
    name: 'Test setup-binary action'
    runs-on: "${{ inputs.runs-on || 'self-hosted' }}"
    steps:
      - name: 'Setup abc'
        uses: 'abcxyz/actions/.github/actions/setup-binary@f26869a425d0b0217b9c8ad7e3f6ab70547272c9' # ratchet:main
        with:
          download_url: 'https://github.com/abcxyz/abc/releases/download/v0.10.1/abc_0.10.1_linux_amd64.tar.gz'
          install_path: '${{ runner.temp }}/.abc'
          binary_subpath: 'abc'
          cache_key: '${{ runner.os }}_${{ runner.arch }}_abc_0.10.1'
          add_to_path: true
      - name: 'Use abc'
        run: 'abc templates describe github.com/abcxyz/abc/t/rest_server@v0.10.0'

  build-and-push-runner:
    name: 'Build and Push Runner'
    uses: './.github/workflows/build_runner.yml'
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      runs-on: "${{ inputs.runs-on || 'self-hosted' }}"
