# Copyright 2025 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Minty Integration Test'

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'The runner environment to use.'
        required: false
        type: 'string'
        default: 'self-hosted'

permissions:
  id-token: 'write'
  contents: 'read'

concurrency:
  # Only allow one at a time as PR update is global.
  group: '${{ github.workflow }}'

jobs:
  write_pr:
    runs-on: '${{ inputs.runs-on }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4
        with:
          ref: 'main'
      - name: 'Create file'
        run: 'echo "hello" > ignore_me'
      - name: 'Mint Token'
        id: 'mint-token'
        uses: 'abcxyz/github-token-minter/.github/actions/mint-token@6c5fb9321c0304db1023a95cf9c289f69f74b838' # ratchet:abcxyz/github-token-minter/.github/actions/mint-token@main
        with:
          wif_provider: '${{ vars.TOKEN_MINTER_WIF_PROVIDER }}'
          wif_service_account: '${{ vars.TOKEN_MINTER_WIF_SERVICE_ACCOUNT }}'
          service_audience: '${{ vars.TOKEN_MINTER_SERVICE_AUDIENCE }}'
          service_url: '${{ vars.TOKEN_MINTER_SERVICE_URL }}'
          requested_permissions: |-
            {
              "scope": "make-pr",
              "repositories": ["github-action-dispatcher"],
              "permissions": {
                "pull_requests": "write",
                "contents": "write"
              }
            }
      - name: 'Create/Update Pull Request'
        uses: 'abcxyz/actions/.github/actions/create-pull-request@main' # ratchet:exclude
        with:
          token: '${{ steps.mint-token.outputs.token }}'
          base_branch: '${{ github.event.repository.default_branch }}'
          head_branch: 'actions/integration-test-create-pr'
          title: '[automated][do not merge] Minty Test Pull Request'
          body: 'Ensuring a self-hosted runner is able to update a PR'
          changed_paths: '["ignore_me"]'
      - name: 'Check Pull Request Updated'
        shell: 'bash'
        run: |-
          gh pr -R abcxyz/github-action-dispatcher list \
          --search "Minty Test Pull Request updated:>=$(date -u -Iseconds -d "1 minute ago")" \
          --limit 1 \
          --json id \
          | js ".[0].id" -e
