name: 'Promote to Production'

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'The commit SHA of the image to promote to production.'
        required: true
        type: 'string'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'

env:
  WIF_PROVIDER: 'projects/727875687543/locations/global/workloadIdentityPools/github-actions-on-gcp-p-a63b4c/providers/github-actions-on-gcp-p-a63b4c'
  WIF_SERVICE_ACCOUNT: 'github-automation-bot@gha-on-gcp-p-a63b4c.iam.gserviceaccount.com'

  DOCKER_REGISTRY: 'us-docker.pkg.dev'
  DOCKER_REPO: 'us-docker.pkg.dev/ghss-artifacts-p-25/docker-images'
  IMAGE_NAME: 'gha-webhook'

  PRODUCTION_SERVICE_NAME: 'action-dispatcher-fed9'
  PRODUCTION_PROJECT_ID: 'action-dispatcher-webhook-p-18'
  PRODUCTION_REGION: 'us-central1'
  RUNNER_LABEL: 'self-hosted'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  promote-to-production:
    name: 'Promote to Production'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@98ddc00a17442e89a24bbf282954a3b65ce6d200' # ratchet:google-github-actions/setup-gcloud@v2
        with:
          version: '529.0.0'

      - name: 'Deploy to Cloud Run'
        run: |-
          gcloud run services update ${{ env.PRODUCTION_SERVICE_NAME }} \
            --project="${{ env.PRODUCTION_PROJECT_ID }}" \
            --region="${{ env.PRODUCTION_REGION }}" \
            --image="${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}-amd64" \
            --update-env-vars="RUNNER_LABEL=${{ env.RUNNER_LABEL }}"
