name: 'Promote Runner to Staging'

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'The image tag (e.g., a commit SHA) to tag as next'
        required: true
        type: 'string'
        default: 'latest'

env:
  WIF_PROVIDER: 'projects/727875687543/locations/global/workloadIdentityPools/github-actions-on-gcp-p-a63b4c/providers/github-actions-on-gcp-p-a63b4c'
  WIF_SERVICE_ACCOUNT: 'github-automation-bot@gha-on-gcp-p-a63b4c.iam.gserviceaccount.com'
  GAR_LOCATION: 'us'
  GAR_IMAGE_NAME: 'ghss-artifacts-p-25/docker-images/gha-runner'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  promote-to-staging:
    name: 'Promote to Staging'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955' # ratchet:actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@e427ad8a34f8676edf47cf7d7925499adf3eb74f' # ratchet:google-github-actions/setup-gcloud@v2
        with:
          version: '529.0.0'

      - uses: 'docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc' # ratchet:docker/login-action@v2
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: 'Tag and Push Image to next'
        run: |
          set -e
          IMAGE_URI="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GAR_IMAGE_NAME }}"
          FULL_IMAGE_NAME="${IMAGE_URI}:${{ github.event.inputs.image-tag }}"

          echo "Pulling image: ${FULL_IMAGE_NAME}"
          docker pull "${FULL_IMAGE_NAME}"

          echo "Tagging ${FULL_IMAGE_NAME} as ${IMAGE_URI}:next"
          docker tag "${FULL_IMAGE_NAME}" "${IMAGE_URI}:next"

          echo "Pushing ${IMAGE_URI}:next"
          docker push "${IMAGE_URI}:next"
