name: 'Self-Hosted Smoke Tests'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  workflow_run:
    # Run this workflow after either of the other build/deploys run.
    workflows:
      - 'build_runner.yml'
      - 'build_webhook.yml'
    types:
      - 'completed'
    branches:
      - 'main'

jobs:
  simple-action-check:
    name: 'Check simple actions on the self-hosted runner'
    runs-on: 'self-hosted'
    steps:
      # https://github.com/google/github_actions_on_gcp/issues/31
      - name: 'Set up Python 3.12'
        uses: 'actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065' # ratchet:actions/setup-python@v5
        with:
          python-version: '3.12'

  check-docker-volume-mount:
    # This test is to check Docker-in-Docker volume mounting. It's possible that the docker run command will succeed but not properly mount the files and workflows subsequently fail.
    name: 'Verify Docker-in-Docker volume mounts on the self-hosted runner'
    runs-on: 'self-hosted'
    steps:
      - name: 'Checkout Repository'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - name: 'Test GITHUB_WORKSPACE mount inside Docker'
        id: 'mount-check'
        shell: 'bash'
        run: |
          echo "Host GITHUB_WORKSPACE is: $GITHUB_WORKSPACE"
          echo "Contents of GITHUB_WORKSPACE on host:"
          ls -laR "$GITHUB_WORKSPACE"

          echo "Running Docker container to check mounted workspace..."
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/github/workspace" \
            -w "/github/workspace" \
            alpine sh -c "ls -laR" > docker_ls_output.txt

          echo "--- Output from inside container (docker_ls_output.txt) ---"
          cat docker_ls_output.txt
          echo "---------------------------------------------------------"

          if grep -q "terraform" docker_ls_output.txt; then
            echo "::notice file=check-docker-volume-mount.yml::Docker volume mount appears to be working correctly."
            echo "status=PASSED" >> "$GITHUB_OUTPUT"
          else
            echo "::error file=check-docker-volume-mount.yml::Docker volume mount failed or is empty."
            echo "status=FAILED" >> "$GITHUB_OUTPUT"
            exit 1 # Fail the step if the mount is empty
          fi
