# Copyright 2025 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'smoke-tests'

on:
  workflow_call:

concurrency:
  group: 'smoke-tests'
  cancel-in-progress: false

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy-runner-discovery-job:
    uses: './.github/workflows/deploy-integration.yml' # ratchet:exclude
    with:
      deploy_dispatcher: false
      deploy_discovery: true
      supported_runner_labels: 'github-action-dispatcher-integration,self-hosted'

  deploy-dispatcher-with-default:
    uses: './.github/workflows/deploy-integration.yml' # ratchet:exclude
    with:
      deploy_dispatcher: true
      deploy_discovery: false
      supported_runner_labels: 'github-action-dispatcher-integration,github-action-dispatcher-2-integration,self-hosted'
      dispatcher_runner_label_aliases: 'self-hosted=github-action-dispatcher-integration'
      dispatcher_disable_default: false

  # Initially this org-pool is not setup in the discovery job so when the
  # dispatcher looks it up it is missing. The dispatcher allows this label but
  # there is no default pool configured for this label.
  # This should fail with 404 on runs-on label.
  test-missing-org-pool-does-not-default:
    name: 'test-missing-org-pool-default-success[FAILURE_EXPECTED]'
    needs: ['deploy-dispatcher-with-default', 'deploy-runner-discovery-job']
    runs-on: 'github-action-dispatcher-2-integration'
    steps:
      - name: 'I SHOULD NOT RUN'
        run: |
          echo "OH NO..."

  # This pool is only configured for default.
  test-finds-default-pool:
    name: 'test-finds-default-pool[SUCCESS_EXPECTED]'
    needs: ['deploy-dispatcher-with-default', 'deploy-runner-discovery-job']
    runs-on: 'github-action-dispatcher-integration'
    steps:
      - name: 'I SHOULD RUN'
        run: |
          echo "OH YEAH..."

  # This aliased pool is only configured for default.
  test-finds-default-pool-with-alias:
    name: 'test-finds-default-pool-with-alias[SUCCESS_EXPECTED]'
    needs: ['deploy-dispatcher-with-default', 'deploy-runner-discovery-job']
    runs-on: 'self-hosted'
    steps:
      - name: 'I SHOULD RUN'
        run: |
          echo "OH YEAH..."

  # This should fail with 404 on runs-on label.
  test-unknown-label:
    name: 'test-unknown-label[FAILURE_EXPECTED]'
    needs: ['deploy-dispatcher-with-default', 'deploy-runner-discovery-job']
    runs-on: 'label-no-run-me'
    steps:
      - name: 'I SHOULD NOT RUN'
        run: |
          echo "OH NO..."

  # After disabling default fallback, only pools configured to directly handle
  # the abcxyz org should pick up jobs. Otherwise they go to the 404 runner.
  # No pools initially are configured in the discovery that have the abcxyz org
  # scope. So ALL JOBS SHOULD FAIL.
  deploy-dispatcher-no-default:
    needs: ['test-finds-default-pool', 'test-finds-default-pool-with-alias']
    uses: './.github/workflows/deploy-integration.yml' # ratchet:exclude
    with:
      deploy_dispatcher: true
      deploy_discovery: false
      supported_runner_labels: 'github-action-dispatcher-integration,github-action-dispatcher-2-integration,self-hosted'
      dispatcher_runner_label_aliases: 'self-hosted=github-action-dispatcher-integration'
      dispatcher_disable_default: true

  # We induce a sleep so that we can confirm that some time delta occurred and
  # that indeed deploying the dispatcher with the job-2 runs-on label
  # correctly picks up the pending job from test-go-version.
  sleep-1-min:
    needs: ['deploy-dispatcher-no-default']
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Sleep 60 seconds'
        run: |
          sleep 60s

  test-does-not-find-default-pool:
    name: 'test-does-not-find-default-pool[FAILURE_EXPECETED]'
    needs: ['deploy-dispatcher-no-default']
    runs-on: 'github-action-dispatcher-integration'
    steps:
      - name: 'I SHOULD RUN'
        run: |
          echo "OH YEAH..."

  # This should fail with 404 on runs-on label because the label is allowlisted,
  # there is no assigned pool, and fallback to default runners is disabled.
  test-does-not-find-missing-org-pool:
    name: 'test-does-not-find-missing-org-pool[FAILURE_EXPECETED]'
    needs: ['deploy-dispatcher-no-default']
    runs-on: 'github-action-dispatcher-2-integration'
    steps:
      - name: 'I SHOULD NOT RUN'
        run: |
          echo "OH NO..."

  # Now we turn on the github-action-dispatcher-2-integration pool which is
  # scoped to abcxyz org. So this jobs sent to this label should succeed.
  deploy-runner-discovery-job-with-runner-2:
    needs: ['sleep-1-min']
    uses: './.github/workflows/deploy-integration.yml' # ratchet:exclude
    with:
      deploy_dispatcher: false
      deploy_discovery: true
      supported_runner_labels: 'github-action-dispatcher-integration,github-action-dispatcher-2-integration,self-hosted'

  # This should now succeed because we have an assigned pool for this.
  test-found-pool-for-label-after-discovery-updates-with-label:
    name: 'test-gad-2-label-in-discovery[SUCCESS_EXPECTED]'
    needs: ['deploy-runner-discovery-job-with-runner-2']
    runs-on: 'github-action-dispatcher-2-integration'
    steps:
      - name: 'I SHOULD RUN'
        run: |
          echo "OH YAY..."

  smoke-tests-passed:
    if: |-
      ${{ always() }}
    needs: [
      # FAILURES
      'test-missing-org-pool-does-not-default',
      'test-unknown-label',
      'test-does-not-find-default-pool',
      'test-does-not-find-missing-org-pool',
      # SUCCESSES
      'test-finds-default-pool',
      'test-finds-default-pool-with-alias',
      'test-found-pool-for-label-after-discovery-updates-with-label'
      ]
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    steps:
      #############
      # FAILURES
      #############
      - name: 'Assert test-missing-org-pool-does-not-default fails'
        if: |-
          ${{ needs.test-missing-org-pool-does-not-default.result != 'failure' }}
        run: |
          echo "::error::Smoke Test succeeded or was skipped. Expected failure. Failing status check to block merge."
          echo "::error::Status: ${{ needs.test-missing-org-pool-does-not-default.result }}"
          exit 1

      - name: 'Assert test-unknown-labal fails'
        if: |-
          ${{ needs.test-unknown-label.result != 'failure' }}
        run: |
          echo "::error::Smoke Test succeeded or was skipped. Expected failure. Failing status check to block merge."
          echo "::error::Status: ${{ needs.test-unknown-label.result }}"
          exit 1

      - name: 'Assert test-does-not-find-default-pool fails'
        if: |-
          ${{ needs.test-does-not-find-default-pool.result != 'failure' }}
        run: |
          echo "::error::Smoke Test succeeded or was skipped. Expected failure. Failing status check to block merge."
          echo "::error::Status: ${{ needs.test-does-not-find-default-pool.result }}"
          exit 1

      - name: 'Assert test-does-not-find-missing-org-pool Test fails'
        if: |-
          ${{ needs.test-does-not-find-missing-org-pool.result != 'failure' }}
        run: |
          echo "::error::Smoke Test succeeded or was skipped. Expected failure. Failing status check to block merge."
          echo "::error::Status: ${{ needs.test-does-not-find-missing-org-pool.result }}"
          exit 1
      #############
      # SUCCESSES
      #############
      - name: 'Assert test-finds-default-pool succeeds'
        if: |-
          ${{ needs.test-finds-default-pool.result != 'success' }}
        run: |
          echo "::error::Smoke Test failed or was skipped. Expected success. Failing status check to block merge."
          echo "::error::Status: ${{ needs.test-finds-default-pool.result }}"
          exit 1

      - name: 'Assert test-finds-default-pool-with-alias succeeds'
        if: |-
          ${{ needs.test-finds-default-pool-with-alias.result != 'success' }}
        run: |
          echo "::error::Smoke Test failed or was skipped. Expected success. Failing status check to block merge."
          echo "::error::Status: ${{ needs.test-finds-default-pool-with-alias.result }}"
          exit 1

      - name: 'Assert test-found-pool-for-label-after-discovery-updates-with-label succeeds'
        if: |-
          ${{ needs.test-found-pool-for-label-after-discovery-updates-with-label.result != 'success' }}
        run: |
          echo "::error::Smoke Test failed or was skipped. Expected success. Failing status check to block merge."
          echo "::error::Status: ${{ needs.test-found-pool-for-label-after-discovery-updates-with-label.result }}"
          exit 1

      - name: 'Confirm tests passed'
        run: 'echo \"Smoke tests succeeded\"'
