# Copyright 2025 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'smoke-tests'

on:
  workflow_call:
    inputs:
      docker_repo:
        type: 'string'
        description: 'The docker repo to deploy from'
      docker_tag:
        type: 'string'
        description: 'The tag to use when deploying images'
      image_name:
        type: 'string'
        description: 'The name of the image to deploy'
      runner_docker_repo:
        type: 'string'
        description: 'The github-action-runner docker repo'
      runner_image_tag:
        type: 'string'
        description: 'The github-action-runner docker image tag'
      runner_image_name:
        type: 'string'
        description: 'The github-action-runner docker image name'
      integration_wif_provider:
        type: 'string'
        description: 'The wif to auth as'
      integration_wif_service_account:
        type: 'string'
        description: 'The wif sa to auth as'

concurrency:
  group: 'smoke-tests'
  cancel-in-progress: false

env:
  DOCKER_REPO: '${{ inputs.docker_repo }}'
  DOCKER_TAG: '${{ inputs.docker_tag }}'
  IMAGE_NAME: '${{ inputs.image_name }}'
  RUNNER_DOCKER_REPO: '${{ inputs.runner_docker_repo }}'
  RUNNER_IMAGE_TAG: '${{ inputs.runner_image_tag }}'
  RUNNER_IMAGE_NAME: '${{ inputs.runner_image_name }}'
  INTEGRATION_WIF_PROVIDER: '${{ inputs.integration_wif_provider }}'
  INTEGRATION_WIF_SERVICE_ACCOUNT: '${{ inputs.integration_wif_service_account }}'

  INTEGRATION_RUNNER_LABEL_SELF_HOSTED: 'self-hosted'
  INTEGRATION_RUNNER_LABEL_GAD_1: 'github-action-dispatcher-integration' # <repo-name>-<env>
  INTEGRATION_RUNNER_LABEL_GAD_2: 'github-action-dispatcher-2-integration' # <repo-name>-<env>
  INTEGRATION_RUNNER_LOCATION: 'us-central1'
  INTEGRATION_RUNNER_PROJECT_ID: 'abcxyz-runner-i-4f'
  INTEGRATION_RUNNER_FOLDER_ID: '961583394935' # deployments/gcb-runner/integration folder
  INTEGRATION_RUNNER_SERVICE_ACCOUNT: 'projects/abcxyz-runner-i-4f/serviceAccounts/runner-sa@abcxyz-runner-i-4f.iam.gserviceaccount.com'
  INTEGRATION_REDIS_HOST: '172.16.0.3'
  INTEGRATION_REDIS_PORT: '6379'

  INTEGRATION_GH_APP_INSTALLATION_ID: '2320897'
  INTEGRATION_PROJECT_ID: 'github-action-dispatcher-i-e3'
  INTEGRATION_REGION: 'us-central1'
  INTEGRATION_SERVICE_NAME: 'github-action-dispatcher-8aa2'
  INTEGRATION_SERVICE_ACCOUNT: 'gad-webhook-sa@github-action-dispatcher-i-e3.iam.gserviceaccount.com'
  INTEGRATION_WORKER_POOL_ID: 'projects/abcxyz-runner-i-4f/locations/us-central1/workerPools/abcxyz-n2d-standard-2'
  INTEGRATION_RUNNER_DISCOVERY_JOB_NAME: 'runner-discovery'
  INTEGRATION_RUNNER_DISCOVERY_JOB_SA: 'runner-discovery-job-sa@github-action-dispatcher-i-e3.iam.gserviceaccount.com'

jobs:
  deploy-runner-discovery-job:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      labels_json: '${{ steps.labels.outputs.labels_json }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.INTEGRATION_WIF_PROVIDER }}'
          service_account: '${{ env.INTEGRATION_WIF_SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a' # ratchet:google-github-actions/setup-gcloud@v2
        with:
          version: '529.0.0'

      - name: 'Deploy to Cloud Run Job'
        id: 'deploy-job'
        run: |-
          cat > /tmp/env_vars <<EOF
          GCP_FOLDER_ID: '${{ env.INTEGRATION_RUNNER_FOLDER_ID }}'
          GCP_ALLOWED_PROJECT_LABEL_GH_ORG_SCOPE_VALUES: 'default'
          GCP_ALLOWED_PROJECT_LABEL_JOB_RUNS_ON_VALUES: '${{ env.INTEGRATION_RUNNER_LABEL_GAD_1 }},${{ env.INTEGRATION_RUNNER_LABEL_SELF_HOSTED }}'
          GCP_ALLOWED_PROJECT_LABEL_POOL_LOCATION_VALUES: '${{ env.INTEGRATION_RUNNER_LOCATION }}'
          GCP_ALLOWED_PROJECT_LABEL_POOL_AVAILABILITY_VALUES: 'available,unavailable'
          GCP_ALLOWED_PROJECT_LABEL_POOL_TYPE_VALUES: 'trusted,private'
          REDIS_HOST: '${{ env.INTEGRATION_REDIS_HOST }}'
          REDIS_PORT: '${{ env.INTEGRATION_REDIS_PORT }}'
          EOF

          gcloud run jobs update "${{ env.INTEGRATION_RUNNER_DISCOVERY_JOB_NAME }}" \
            --project="${{ env.INTEGRATION_PROJECT_ID }}" \
            --region="${{ env.INTEGRATION_REGION }}" \
            --env-vars-file=/tmp/env_vars \
            --image="${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}-amd64"

      - name: 'Execute Discovery Job'
        run: |-
          gcloud run jobs execute "${{ env.INTEGRATION_RUNNER_DISCOVERY_JOB_NAME }}" \
            --project="${{ env.INTEGRATION_PROJECT_ID }}" \
            --region="${{ env.INTEGRATION_REGION }}" \
            --wait

      - name: 'Set label outputs'
        id: 'labels'
        run: |-
          labels_json="['${{ env.INTEGRATION_RUNNER_LABEL_GAD_1 }}','${{ env.INTEGRATION_RUNNER_LABEL_GAD_2 }}','${{ env.INTEGRATION_RUNNER_LABEL_SELF_HOSTED }}']"
          echo "labels_json=${labels_json}"
          echo "labels_json=${labels_json}" >> "${GITHUB_OUTPUT}"

  deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      GITHUB_APP_ID: '2320897'
      KMS_APP_PRIVATE_KEY_ID: 'projects/github-action-dispatcher-i-e3/locations/us-central1/keyRings/gad-71-key-ring/cryptoKeys/gad-71-pk/cryptoKeyVersions/1'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.INTEGRATION_WIF_PROVIDER }}'
          service_account: '${{ env.INTEGRATION_WIF_SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a' # ratchet:google-github-actions/setup-gcloud@v2
        with:
          version: '529.0.0'

      - name: 'Deploy to Cloud Run'
        id: 'deploy'
        run: |-
          WEBHOOK_SECRET_MOUNT_PATH="/etc/secrets/webhook/key"
          WEBHOOK_SECRET_NAME="webhook-key"
          WEBHOOK_SECRET_VERSION="latest"

          cat > /tmp/env_vars <<EOF
          REDIS_HOST: '${{ env.INTEGRATION_REDIS_HOST }}'
          REDIS_PORT: '${{ env.INTEGRATION_REDIS_PORT }}'
          EXTRA_RUNNER_COUNT: '0'
          GITHUB_APP_ID: '${{ env.GITHUB_APP_ID }}'
          KMS_APP_PRIVATE_KEY_ID: '${{ env.KMS_APP_PRIVATE_KEY_ID }}'
          RUNNER_IMAGE_NAME: '${{ env.RUNNER_IMAGE_NAME }}'
          RUNNER_IMAGE_TAG: '${{ env.RUNNER_IMAGE_TAG }}'
          RUNNER_LOCATION: '${{ env.INTEGRATION_RUNNER_LOCATION }}'
          RUNNER_PROJECT_ID: '${{ env.INTEGRATION_RUNNER_PROJECT_ID }}'
          RUNNER_REPOSITORY_ID: '${{ env.RUNNER_DOCKER_REPO }}'
          RUNNER_SERVICE_ACCOUNT: '${{ env.INTEGRATION_RUNNER_SERVICE_ACCOUNT }}'
          RUNNER_WORKER_POOL_ID: '${{ env.INTEGRATION_WORKER_POOL_ID }}'
          RUNNER_LABEL_ALIASES: '${{ env.INTEGRATION_RUNNER_LABEL_SELF_HOSTED }}=${{ env.INTEGRATION_RUNNER_LABEL_GAD_1 }}'
          SUPPORTED_RUNNER_LABELS: '${{ env.INTEGRATION_RUNNER_LABEL_GAD_1 }},${{ env.INTEGRATION_RUNNER_LABEL_GAD_2 }},${{ env.INTEGRATION_RUNNER_LABEL_SELF_HOSTED }}'
          WEBHOOK_KEY_MOUNT_PATH: '${WEBHOOK_SECRET_MOUNT_PATH}'
          WEBHOOK_KEY_NAME: '${WEBHOOK_SECRET_NAME}'
          EOF

          gcloud run deploy "${{ env.INTEGRATION_SERVICE_NAME }}" \
            --project="${{ env.INTEGRATION_PROJECT_ID }}" \
            --region="${{ env.INTEGRATION_REGION }}" \
            --service-account="${{ env.INTEGRATION_SERVICE_ACCOUNT }}" \
            --image="${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}-amd64" \
            --ingress=internal-and-cloud-load-balancing \
            --no-allow-unauthenticated \
            --set-secrets="${WEBHOOK_SECRET_MOUNT_PATH}/${WEBHOOK_SECRET_NAME}=${WEBHOOK_SECRET_NAME}:${WEBHOOK_SECRET_VERSION}" \
            --env-vars-file=/tmp/env_vars \
            --format='value(status.url)'

  # We expect test-go-version[github-action-dispatcher-2-integration] not to be
  # initially picked up until deploy-runner-discovery-job-with-runner-2 runs ~1-2 minutes later.
  test-go-version:
    name: 'test-go-version[${{ matrix.target_label }}][${{ github.sha }}]'
    needs: ['deploy', 'deploy-runner-discovery-job']
    strategy:
      matrix:
        target_label: '${{ fromJson(needs.deploy-runner-discovery-job.outputs.labels_json) }}'
    runs-on: '${{ matrix.target_label }}'
    steps:
      - name: 'Setup Go'
        uses: 'actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b' # ratchet:actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: 'Check Go version'
        run: |
          echo "Checking Go version on self-hosted runner..."
          go version

  # We induce a sleep so that we can confirm that some time delta occurred and
  # that indeed deploying the dispatcher with the job-2 runs-on label
  # correctly picks up the pending job from test-go-version.
  sleep_1_min:
    needs: ['deploy', 'deploy-runner-discovery-job']
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Sleep 60 seconds'
        run: |
          sleep 60s

  deploy-runner-discovery-job-with-runner-2:
    runs-on: 'ubuntu-latest'
    needs: ['sleep_1_min']
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      deploy_time: '${{ steps.time.outputs.deploy_time }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.INTEGRATION_WIF_PROVIDER }}'
          service_account: '${{ env.INTEGRATION_WIF_SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a' # ratchet:google-github-actions/setup-gcloud@v2
        with:
          version: '529.0.0'

      - name: 'Deploy to Cloud Run Job'
        id: 'deploy-job'
        run: |-
          cat > /tmp/env_vars <<EOF
          GCP_FOLDER_ID: '${{ env.INTEGRATION_RUNNER_FOLDER_ID }}'
          GCP_ALLOWED_PROJECT_LABEL_GH_ORG_SCOPE_VALUES: 'default'
          GCP_ALLOWED_PROJECT_LABEL_JOB_RUNS_ON_VALUES: '${{ env.INTEGRATION_RUNNER_LABEL_GAD_1 }},${{ env.INTEGRATION_RUNNER_LABEL_GAD_2 }},${{ env.INTEGRATION_RUNNER_LABEL_SELF_HOSTED }}'
          GCP_ALLOWED_PROJECT_LABEL_POOL_LOCATION_VALUES: '${{ env.INTEGRATION_RUNNER_LOCATION }}'
          GCP_ALLOWED_PROJECT_LABEL_POOL_AVAILABILITY_VALUES: 'available,unavailable'
          GCP_ALLOWED_PROJECT_LABEL_POOL_TYPE_VALUES: 'trusted,private'
          REDIS_HOST: '${{ env.INTEGRATION_REDIS_HOST }}'
          REDIS_PORT: '${{ env.INTEGRATION_REDIS_PORT }}'
          EOF

          gcloud run jobs update "${{ env.INTEGRATION_RUNNER_DISCOVERY_JOB_NAME }}" \
            --project="${{ env.INTEGRATION_PROJECT_ID }}" \
            --region="${{ env.INTEGRATION_REGION }}" \
            --env-vars-file=/tmp/env_vars \
            --image="${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}-amd64"

      - name: 'Execute Discovery Job'
        run: |-
          gcloud run jobs execute "${{ env.INTEGRATION_RUNNER_DISCOVERY_JOB_NAME }}" \
            --project="${{ env.INTEGRATION_PROJECT_ID }}" \
            --region="${{ env.INTEGRATION_REGION }}" \
            --wait

      - name: 'Output Deploy time'
        id: 'time'
        run: |-
          deploy_time="$(date +%s%N)"
          echo "deploy_time=${deploy_time}"
          echo "deploy_time=${deploy_time}" >> "${GITHUB_OUTPUT}"

  # This should never execute.
  test-unknown-label:
    name: 'test-unknown-label[${{ github.sha }}]'
    needs: ['deploy', 'deploy-runner-discovery-job']
    runs-on: 'label-no-run-me'
    steps:
      - name: 'I SHOULD NOT RUN'
        run: |
          echo "OH NO..."

  # We assume that 4 minutes is sufficient for the job to be picked up under
  # normal operating circumstances. Note that if there is some intermitent
  # failure or outage with GitHub this may not be sufficient.
  sleep_4_min:
    needs: ['deploy', 'deploy-runner-discovery-job']
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Sleep 240 seconds'
        run: |
          sleep 240s

  cancel-or-fail-unknown-label:
    if: |-
      ${{ always() }}
    needs: ['sleep_4_min', 'deploy-runner-discovery-job-with-runner-2', 'test-go-version']
    runs-on: 'ubuntu-latest'
    permissions:
      actions: 'write'
    steps:
      - name: 'Echo Success'
        env:
          JOB_NAME: 'test-unknown-label[${{ github.sha }}]'
          GH_TOKEN: '${{ github.token }}'
          RUN_ID: '${{ github.run_id }}'
        run: |
          JOB_STATUS=$(gh run view "${RUN_ID}" --json jobs -q '.jobs[] | select(.name == "${JOB_NAME}") | .status')

          if [[ "$JOB_STATUS" == "queued" ]]; then
            echo "Successfully verified that 'label-no-run-me' is queued."
            echo "Cancelling the workflow run..."
            curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "${REPO_URL}/actions/runs/${RUN_ID}/cancel"
            echo "Workflow run cancellation initiated."
            exit 0
          else
            echo "Error: 'label-no-run-me' is not in the expected 'queued' state. Current status: ${JOB_STATUS}"
            exit 1
          fi

  confirm-test-go-version-ran:
    if: |-
      ${{ always() }}
    needs: ['deploy-runner-discovery-job-with-runner-2', 'test-go-version', 'cancel-or-fail-unknown-label']
    runs-on: 'ubuntu-latest'
    steps:
      # TODO: Confirm that the execution time for the test-go-version[github-action-dispatcher-2-integration]
      #       job was after needs.deploy-runner-discovery-job-with-runner-2.outputs.deploy_time
      - name: 'Echo Success'
        run: |
          echo "All expected jobs ran!"
